In [1]:
import torch
import cv2
import torchvision.transforms as transforms
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
os.chdir("/Users/eugenekim/PycharmProjects/asl-alphabet-classification/data")

In [98]:
numerical_map = {"A":0, "B":1, "C":2, "D":3, "del":4, "E":5, "F":6,
                "G":7,"H":8,"I":9,"J":10,"K":11,"L":12,"M":13,"N":14,
                "nothing":15,"O":16,"P":17,"Q":18,"R":19,"S":20,
                 "space":21,"T":22,"U":23,"V":24,"W":25,"X":26,"Y":27,"Z":28}

In [121]:
file_path = "./raw_data"

transform = transforms.Compose([transforms.ToTensor()])

def get_asl_data(split="train", normalized=False):
    
    #Desired parameters
    inputs = "empty"
    
    #Loop through data file
    for data in sorted(os.listdir(file_path)):
        if data == "asl_alphabet_test":
                
            for letter in sorted(os.listdir(os.path.join(file_path,data))):

                #Check if image ends with ".jpg"
                if not letter.endswith(".jpg"):
                    continue

                #Read image
                read_image = cv2.imread(os.path.join(file_path,data,letter))

                #Convert to RGB
                temp_image = cv2.cvtColor(read_image, cv2.COLOR_BGR2RGB)
                
                #Convert the image to tensor
                image_tensor = transform(temp_image)
                
                if inputs == "empty":
                    inputs = image_tensor
                    
                else:
                    inputs = torch.vstack((inputs,image_tensor))
    
        if data == "asl_alphabet_train":
            
            #Desired labels
            outputs = "empty"
            
            for letter in sorted(os.listdir(os.path.join(file_path,data))):
                
                if letter == ".DS_Store":
                    continue
                    
                map_letter = numerical_map[letter]
                    
                if outputs == "empty":
                    outputs = torch.tensor([map_letter])
                    
                else:
                    outputs = torch.vstack((outputs,torch.tensor([map_letter])))
                
                for image in sorted(os.listdir(os.path.join(file_path,data,letter))):
                    if not image.endswith(".jpg"):
                        continue

                    read_image = cv2.imread(os.path.join(file_path,data,letter,image))

                    #Convert to RGB
                    temp_image = cv2.cvtColor(read_image, cv2.COLOR_BGR2RGB)
                    
                    #Convert the image to tensor
                    image_tensor = transform(temp_image)
                    
                    if inputs == "empty":
                        inputs = image_tensor
                    else:
                        inputs = torch.vstack((inputs,image_tensor))
  
                if outputs == "empty":
                    outputs = letter
                    
                else:
                    outputs = torch.vstack((outputs,letter))
                    

In [5]:
file_path = "./raw_data"
transform = transforms.Compose([transforms.ToTensor()])
    
    #Loop through data file
for data in sorted(os.listdir(file_path)):
    if data == "asl_alphabet_test":
        for letter in sorted(os.listdir(os.path.join(file_path,data))):

                    #Check if image ends with ".jpg"
            if not letter.endswith(".jpg"):
                continue

                    #Read image
            read_image = cv2.imread(os.path.join(file_path,data,letter))

                    #Convert to RGB
            temp_image = cv2.cvtColor(read_image, cv2.COLOR_BGR2RGB)

                    #Convert the image to tensor
            image_tensor = transform(temp_image)

    #                 inputs = np.append(inputs, temp_image)

    if data == "asl_alphabet_train":

        for letter in sorted(os.listdir(os.path.join(file_path,data))):

            if letter == ".DS_Store":
                continue
            for image in sorted(os.listdir(os.path.join(file_path,data,letter))):
                if not image.endswith(".jpg"):
                    continue

                read_image = cv2.imread(os.path.join(file_path,data,letter,image))

                        #Convert to RGB
                temp_image = cv2.cvtColor(read_image, cv2.COLOR_BGR2RGB)
                print(temp_image)
                        #Convert the image to tensor
                image_tensor = transform(temp_image)

                print(type(image_tensor))
                break
            break
    


[[[  1   2 252]
  [  1   0 248]
  [ 10   0 249]
  ...
  [  4   0 248]
  [  3   4 252]
  [  0   0 246]]

 [[  1   1 249]
  [  3   1 234]
  [ 15   6 209]
  ...
  [ 17   6 198]
  [  4   2 210]
  [  6  11 227]]

 [[  0   0 241]
  [ 10   8 206]
  [ 39  32 144]
  ...
  [189 173 244]
  [174 165 255]
  [ 11   7 164]]

 ...

 [[  5   3 254]
  [  3   3 195]
  [129 135 213]
  ...
  [144 129 158]
  [135 125 224]
  [ 17   9 144]]

 [[  0   0 251]
  [  4   8 219]
  [120 124 255]
  ...
  [136 126 225]
  [118 114 253]
  [ 15  13 172]]

 [[  0   1 251]
  [  2   6 227]
  [  7  10 173]
  ...
  [ 19  11 146]
  [ 17  13 172]
  [  7   7 179]]]
<class 'torch.Tensor'>


In [6]:
class ASLDataset(Dataset):
    
    def __init__(self, csv_file, root_dir, transform=None):
        self.csv_file = pd.read_csv(csv_file)
        self.root_dir = root_dir
        self.transform = transform
        
    def __len__(self):
        return len(self.csv_file)
    
    def __getitem__(self, idx):
        

SyntaxError: unexpected EOF while parsing (<ipython-input-6-678bd1130158>, line 12)

In [50]:
x = torch.randn(3,2, 3)
x

tensor([[[ 0.4982, -1.1242,  1.1630],
         [-0.2272,  1.3963, -0.3712]],

        [[-0.2285,  0.5456, -0.3234],
         [ 0.5971,  0.1079,  1.4651]],

        [[-0.3058,  1.8598,  0.3218],
         [-0.9250,  0.1210,  0.5844]]])

In [51]:
y = torch.stack((x,x),3)

In [53]:
y

tensor([[[[ 0.4982,  0.4982],
          [-1.1242, -1.1242],
          [ 1.1630,  1.1630]],

         [[-0.2272, -0.2272],
          [ 1.3963,  1.3963],
          [-0.3712, -0.3712]]],


        [[[-0.2285, -0.2285],
          [ 0.5456,  0.5456],
          [-0.3234, -0.3234]],

         [[ 0.5971,  0.5971],
          [ 0.1079,  0.1079],
          [ 1.4651,  1.4651]]],


        [[[-0.3058, -0.3058],
          [ 1.8598,  1.8598],
          [ 0.3218,  0.3218]],

         [[-0.9250, -0.9250],
          [ 0.1210,  0.1210],
          [ 0.5844,  0.5844]]]])